### ISSUE TITLE
Add and Delete cells inside the big cell 

### ISSUE THREAD

**Issue by nelsaow** [Ullas9/Collection-View-add-remove-new-cell-on-click#1]
Hello Ullas!

Do you have any writings about Add and Delete cells inside the big cell ?

**Comment by Ullas9** [comment]
yes you mean to create a cell inside a cell ??

**Comment by Ullas9** [comment]
// INSIDE VIEW CONTROLLER

import UIKit

class ViewController: UITableViewController {

    let data: [AnyObject] = ["one\ntwo\nthree" as AnyObject, "cat\ndog\nhorse" as AnyObject, ["apple", "bannana", "carrot"] as AnyObject]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        tableView.register(UINib(nibName: "tableCell", bundle: nil), forCellReuseIdentifier: "table")
        tableView.register(UINib(nibName: "textCell", bundle: nil), forCellReuseIdentifier: "text")
        
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 50
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return data.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        if let data = data[indexPath.row] as? [AnyObject] {
            let cell: TableCell = tableView.dequeueReusableCell(withIdentifier: "table")! as! TableCell
            cell.data = data
            cell.backgroundColor = UIColor.orange
            cell.childTableView.dataSource = cell
            return cell
        } else {
            let cell: TextCell = tableView.dequeueReusableCell(withIdentifier: "text")! as! TextCell
            cell.textView.text = "\(data[indexPath.row])"
            cell.backgroundColor = UIColor.lightGray
            return cell
        }
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if let data = data[indexPath.row] as? [AnyObject] {
//            return 200
        }
        
        return UITableViewAutomaticDimension
    }
    
    
    
}


////INSIDE TABLE VIEW CELL


import Foundation
import UIKit

class TableCell: UITableViewCell, UITableViewDataSource {
    
    var data: [AnyObject]!
    
    @IBOutlet weak var childTableView: UITableView!
    
    override func awakeFromNib() {
        childTableView.register(UINib(nibName: "tableCell", bundle: nil), forCellReuseIdentifier: "table")
        childTableView.register(UINib(nibName: "textCell", bundle: nil), forCellReuseIdentifier: "text")
        
        childTableView.rowHeight = UITableViewAutomaticDimension
        childTableView.estimatedRowHeight = 50

    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return data.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        if let data = data[indexPath.row] as? [String] {
            let cell: TableCell = tableView.dequeueReusableCell(withIdentifier: "table")! as! TableCell
            cell.data = data as [AnyObject]!
            cell.backgroundColor = UIColor.orange
            return cell
        } else {
            let cell: TextCell = tableView.dequeueReusableCell(withIdentifier: "text")! as! TextCell
            cell.textView.text = "\(data[indexPath.row])"
            cell.backgroundColor = UIColor.lightGray
            return cell
        }
    }


}
